BoardGameLibrary/Models/Checkout.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BoardGameLibrary.Models
{
    public class Checkout
    {
        public int ID { get; set; }
        [Display(Name = "Checked out at")]
        [DisplayFormat(DataFormatString = "{0:f}")]
        public DateTime TimeOut { get; set; }
        [Display(Name = "Checked in at")]
        [DisplayFormat(DataFormatString = "{0:f}")]
        public DateTime? TimeIn { get; set; }
        [NotMapped]
        [Display(Name = "Checkout length")]
        [DisplayFormat(DataFormatString = "{0:%d} days {0:%h} hours {0:%m} minutes", ApplyFormatInEditMode = true)]
        public TimeSpan Length { 
            get 
            {
                if (TimeIn == null)
                    return DateTime.Now - TimeOut;
                else
                    return TimeIn.Value - TimeOut;
            } 
        }
        public virtual Attendee Attendee { get; set; }

        [InverseProperty("CheckoutHistory")]
        public virtual Copy Copy { get; set; }

        public virtual Play Play { get; set; }
    }
}

BoardGameLibrary/Controllers/CheckoutsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BoardGameLibrary.Data.Models;
using PagedList;
using BoardGameLibrary.Utility;

namespace BoardGameLibrary.Controllers
{
    public class CheckoutsController : VolunteerController
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private AppSettings _appSettings = new AppSettings();

        const string timeOutDescSort = "time_out_desc";
        const string timeOutAscSort = "time_out_asc";
        const string playDescSort = "play_desc";
        const string playAscSort = "play_asc";

        // GET: Checkouts
        public async Task<ActionResult> Index(string currentFilter, string searchString, int? page, string sortOrder = timeOutDescSort)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.TimeOutSort = sortOrder == timeOutDescSort ? timeOutAscSort : timeOutDescSort;
            ViewBag.PlaySort = sortOrder == playDescSort ? playAscSort : playDescSort;
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            int pageSize = _appSettings.PageSize;
            int pageNumber = page ?? 1;

            var results = db.Checkouts.Select(c => c);

            if (!string.IsNullOrWhiteSpace(searchString))
                results = results.Where(c => c.Copy.Game.Title.Contains(searchString)
                                          || c.Copy.LibraryID.ToString().Contains(searchString)
                                          || c.Attendee.Name.Contains(searchString)
                                          || c.Attendee.BadgeID.Contains(searchString));

            switch (sortOrder)
            {
                case playDescSort:
                    results = results.OrderByDescending(c => c.Play == null);
                    break;
                case playAscSort:
                    results = results.OrderBy(c => c.Play == null);
                    break;
                case timeOutDescSort:
                    results = results.OrderByDescending(c => c.TimeOut);
                    break;
                default:
                    results = results.OrderBy(c => c.TimeOut);
                    break;
            }

            return View(results.ToPagedList(pageNumber, pageSize));
        }

        // GET: Checkouts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Checkout checkout = await db.Checkouts.FindAsync(id);
            if (checkout == null)
            {
                return HttpNotFound();
            }
            return View(checkout);
        }

        // GET: Checkouts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Checkouts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,TimeOut,TimeIn")] Checkout checkout)
        {
            if (ModelState.IsValid)
            {
                db.Checkouts.Add(checkout);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(checkout);
        }

        // GET: Checkouts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Checkout checkout = await db.Checkouts.FindAsync(id);
            if (checkout == null)
            {
                return HttpNotFound();
            }
            return View(checkout);
        }

        // POST: Checkouts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,TimeOut,TimeIn")] Checkout checkout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkout).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(checkout);
        }

        // GET: Checkouts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Checkout checkout = await db.Checkouts.FindAsync(id);
            if (checkout == null)
            {
                return HttpNotFound();
            }
            return View(checkout);
        }

        // POST: Checkouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Checkout checkout = await db.Checkouts.FindAsync(id);
            db.Checkouts.Remove(checkout);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BoardGameLibrary/Views/Checkouts/Details.cshtml
@model BoardGameLibrary.Data.Models.Checkout

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Checkout</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TimeOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeIn)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BoardGameLibrary/Views/Checkouts/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<BoardGameLibrary.Data.Models.Checkout>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Checkout History</h2>

@using (Html.BeginForm("Index", "Checkouts", FormMethod.Get, new { @class = "form-inline" }))
{
    <p>
        @Html.TextBox("SearchString", null, new { @class = "form-control text-box", placeholder = "Title, library ID, or attendee name/ID" })
        <input type="submit" value="Search" class="btn btn-primary" />
        
    </p>
}

<table class="checkout-history-table table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.First().Copy)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.First().Attendee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Length)
        </th>
        <th>
            <span class="glyphicon glyphicon-sort"></span>
            @{
                object timeOutLinkOptions = null;
                if (((string)ViewBag.SortOrder).Contains("time_out"))
                {
                    timeOutLinkOptions = new { @class = "current-sort" };
                }
            }
            @Html.ActionLink("Time Out", "Index", new { sortOrder = ViewBag.TimeOutSort }, timeOutLinkOptions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TimeIn)
        </th>
        <th>
            <span class="glyphicon glyphicon-sort"></span>
            @{
                object playLinkOptions = null;
                if (((string)ViewBag.SortOrder).Contains("play"))
                {
                    playLinkOptions = new { @class = "current-sort" };
                }
            }
            @Html.ActionLink("Play Entered", "Index", new { sortOrder = ViewBag.PlaySort }, playLinkOptions)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @string.Format("{0} ({1})", item.Copy.Game.Title, item.Copy.LibraryID)
        </td>
        <td>
            @string.Format("{0} ({1})", item.Attendee.Name, item.Attendee.BadgeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Length)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeOut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeIn)
        </td>
        <td>
            @{
                var playEntered = item.Play != null;
            }
            @playEntered
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.SortOrder }))