BoardGameLibrary/Models/CopyCheckinViewModel.cs
using BoardGameLibrary.Data.Models;
using FluentValidation;
using FluentValidation.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace BoardGameLibrary.Models
{
    [Validator(typeof(CopyCheckinValidator))]
    public class CopyCheckInViewModel
    {
        [Display(Name = "Library ID #")]
        public string CopyLibraryID { get; set; }

        public IList<string> Messages { get; set; }

        public CopyCheckInViewModel()
        {
            Messages = new List<string>();
        }
    }

    public class CopyCheckinValidator : AbstractValidator<CopyCheckInViewModel>
    {
        ApplicationDbContext _db;
        public CopyCheckinValidator()
        {
            _db = new ApplicationDbContext();
            
            RuleFor(x => x.CopyLibraryID).Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage("Library ID required.")
                .Must(Exist).WithMessage("Not found.  Make sure the ID is correct and in the system.")
                .Must(BeCheckedOut).WithMessage("This copy is not checked out.");
        }

        private bool Exist(string copyLibraryID)
        {
            var copyLibraryIDInt = Convert.ToInt32(copyLibraryID.Replace("*", ""));
            if (_db.Copies.AsNoTracking().FirstOrDefault(c => c.LibraryID == copyLibraryIDInt) == null)
                return false;

            return true;
        }

        private bool BeCheckedOut(string copyLibraryID)
        {
            var copyLibraryIDInt = Convert.ToInt32(copyLibraryID.Replace("*", ""));
            var copy = _db.Copies.AsNoTracking().FirstOrDefault(c => c.LibraryID == copyLibraryIDInt);
            var currentCheckout = copy.CurrentCheckout;
            if (currentCheckout == null)
                return false;

            return true;
        }
    }
}

BoardGameLibrary/Models/CopyCheckoutViewModel.cs
using BoardGameLibrary.Data.Models;
using FluentValidation;
using FluentValidation.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace BoardGameLibrary.Models
{
    [Validator(typeof(CopyCheckoutValidator))]
    public class CopyCheckOutViewModel
    {
        [Display(Name = "Library ID #")]
        public string CopyLibraryID { get; set; }
        [Display(Name = "Attendee Badge #")]
        public string AttendeeBadgeID { get; set; }
        [Display(Name = "Override Limit")]
        public bool OverrideLimit { get; set; }
        public IList<string> Messages { get; set; }

        public CopyCheckOutViewModel()
        {
            OverrideLimit = false;
            Messages = new List<string>();
        }
    }

    public class CopyCheckoutValidator : AbstractValidator<CopyCheckOutViewModel>
    {
        ApplicationDbContext _db;
        public CopyCheckoutValidator()
        {
            _db = new ApplicationDbContext();
            var gameAlreadyCheckedOut = "";
            RuleFor(x => x.AttendeeBadgeID).Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage("Badge ID required.")
                .Must(BeAnExistingAttendee).WithMessage("Attendee not found.");
                
            Unless(a => a.OverrideLimit, () => {
                RuleFor(x => x.AttendeeBadgeID).Cascade(CascadeMode.StopOnFirstFailure)
                    .Must(badgeId => NotAlreadyHaveACopyCheckedOut(badgeId, out gameAlreadyCheckedOut))
                                               .WithMessage("Attendee has {0} checked out.", x => gameAlreadyCheckedOut);
            });

            RuleFor(x => x.CopyLibraryID).Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage("You must provide a library ID.")
                .Must(BeANumber).WithMessage("Library IDs must be a number")
                .Must(BeAnExistingGameCopy).WithMessage("Copy not found.")
                .Must(NotBeCheckedOut).WithMessage("That copy is checked out already.  Check it in first.");
        }

        private bool BeANumber(string attendeeBadgeID)
        {
            int parsedInt = 0;
            var parsedSuccessfully = Int32.TryParse(attendeeBadgeID, out parsedInt);

            return parsedSuccessfully;
        }

        private bool BeAnExistingAttendee(string attendeeBadgeID)
        {
            if (_db.Attendees.AsNoTracking().FirstOrDefault(a => a.BadgeID == attendeeBadgeID) == null)
                return false;

            return true;
        }

        private bool NotAlreadyHaveACopyCheckedOut(string attendeeBadgeID, out string gameCheckedOutAlready)
        {
            var currentlyCheckedOutCopy = _db.Copies.AsNoTracking().FirstOrDefault(c => c.CurrentCheckout.Attendee.BadgeID == attendeeBadgeID);
            if (currentlyCheckedOutCopy != null)
            {
                gameCheckedOutAlready = currentlyCheckedOutCopy.Game.Title + "(#" + currentlyCheckedOutCopy.LibraryID + ")";
                return false;
            }

            gameCheckedOutAlready = "";
            return true;
        }

        private bool BeAnExistingGameCopy(string copyLibraryID)
        {
            var copyLibraryIDInt = Convert.ToInt32(copyLibraryID.Replace("*", ""));
            if (_db.Copies.AsNoTracking().FirstOrDefault(c => c.LibraryID == copyLibraryIDInt) == null)
                return false;

            return true;
        }

        private bool NotBeCheckedOut(string copyLibraryID)
        {
            var copyLibraryIDInt = Convert.ToInt32(copyLibraryID.Replace("*", ""));
            var copy = _db.Copies.AsNoTracking().FirstOrDefault(c => c.LibraryID == copyLibraryIDInt);
            if (copy.CurrentCheckout != null)
                return false;

            return true;
        }
    }
}

BoardGameLibrary/Models/CopySearchViewModel.cs
using BoardGameLibrary.Data.Models;
using System.ComponentModel.DataAnnotations;
using FluentValidation;
using FluentValidation.Attributes;

namespace BoardGameLibrary.Models
{
    [Validator(typeof(CopySearchValidator))]
    public class CopySearchViewModel
    {
        [Display(Name = "Title/ID")]
        public string Info { get; set; }

        public bool NavSearch { get; set; }
    }

    public class CopySearchValidator : AbstractValidator<CopySearchViewModel>
    {
        ApplicationDbContext _db;

        public CopySearchValidator()
        {
            _db = new ApplicationDbContext();
            RuleFor(x => x.Info).Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage("You must provide search criteria.");
        }
    }
}

BoardGameLibrary/Controllers/CopiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BoardGameLibrary.Models;
using BoardGameLibrary.Data.Models;

namespace BoardGameLibrary.Controllers
{
    public class CopiesController : VolunteerController
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Copies
        public async Task<ActionResult> Index(int? gameID)
        {
            if (gameID == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.GameID = gameID;

            var game = await _db.Games.FindAsync(gameID.Value);
            ViewBag.GameTitle = game.Title;
            var copies = game.Copies;

            return View(copies);
        }

        // GET: Copies/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copy copy = await _db.Copies.FindAsync(id);
            if (copy == null)
                return HttpNotFound();

            return View(copy);
        }

        // GET: Copies/Create
        public ActionResult Create(int? gameID)
        {
            if (gameID == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var game = _db.Games.FirstOrDefault(g => g.ID == gameID.Value);
            var copy = new Copy { GameID = gameID.Value, Game = game };

            return View(copy);
        }

        // POST: Copies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Copy copy)
        {
            var preExistingCopy = await _db.Copies.FirstOrDefaultAsync(c => c.LibraryID == copy.LibraryID);
            if (preExistingCopy != null)
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);

            var game = await _db.Games.FindAsync(copy.GameID);
            game.Copies.Add(copy);
            if (ModelState.IsValid)
            {
                _db.Copies.Add(copy);
                _db.Entry(game).State = EntityState.Modified;
                await _db.SaveChangesAsync();

                return RedirectToAction("Index", new { gameID = copy.GameID });
            }

            return View(copy);
        }

        // GET: Copies/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Copy copy = await _db.Copies.FindAsync(id);
            if (copy == null)
            {
                return HttpNotFound();
            }
            return View(copy);
        }

        // POST: Copies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Copy copy)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(copy).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index", new { gameID = copy.GameID });
            }
            return View(copy);
        }

        // GET: Copies/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Copy copy = await _db.Copies.FindAsync(id);
            if (copy == null)
                return HttpNotFound();

            return View(copy);
        }

        public async Task<ActionResult> CheckOutCopy(CopyCheckOutViewModel model)
        {
            if (ModelState.IsValid)
            {
                var copyLibraryId = Convert.ToInt32(model.CopyLibraryID.Replace("*", ""));
                var copy = await _db.Copies.FirstOrDefaultAsync(c => c.LibraryID == copyLibraryId);
                var attendee = await _db.Attendees.FirstOrDefaultAsync(a => a.BadgeID == model.AttendeeBadgeID.Replace("*", ""));
                var checkout = new Checkout { TimeOut = DateTime.Now, Attendee = attendee, Copy = copy };
                copy.CurrentCheckout = checkout;

                await _db.SaveChangesAsync();

                model.AttendeeBadgeID = "";
                model.CopyLibraryID = "";
                model.Messages.Add(string.Format("Copy {0} of {1} checked out to {2}({3}).", copyLibraryId, copy.Game.Title, attendee.Name, attendee.BadgeID));
            }
            else
                Response.StatusCode = 400;
            
            return PartialView("_CopyCheckOut", model);
        }

        public async Task<ActionResult> CheckInCopy(CopyCheckInViewModel model)
        {
            if (ModelState.IsValid)
            {
                var copyLibraryId = Convert.ToInt32(model.CopyLibraryID.Replace("*", ""));
                var copy = await _db.Copies.FirstOrDefaultAsync(c => c.LibraryID == copyLibraryId);
                copy.CurrentCheckout.TimeIn = DateTime.Now;
                copy.CheckoutHistory.Add(copy.CurrentCheckout);
                copy.CurrentCheckout = null;

                await _db.SaveChangesAsync();

                model.CopyLibraryID = "";
                model.Messages.Add(string.Format("Copy {0} of {1} checked in.", copy.LibraryID, copy.Game.Title));
            }
            else
                Response.StatusCode = 400;

            return PartialView("_CopyCheckIn", model);
        }

        [HttpPost]
        public async Task<JsonResult> CheckInCopyLight(string copyId)
        {
            if (ModelState.IsValid)
            {
                var copyLibraryId = Convert.ToInt32(copyId.Replace("*", ""));
                var copy = await _db.Copies.FirstOrDefaultAsync(c => c.LibraryID == copyLibraryId);
                copy.CurrentCheckout.TimeIn = DateTime.Now;
                copy.CheckoutHistory.Add(copy.CurrentCheckout);
                copy.CurrentCheckout = null;

                await _db.SaveChangesAsync();

                var msg = string.Format("Copy {0} of {1} checked in.", copy.LibraryID, copy.Game.Title);

                return Json(new { message = msg });
            }
            else
                return Json(new { message = "Failed to check in copy." });
        }

        public async Task<JsonResult> GetCopyGameTitle(string copyId)
        {
            if (ModelState.IsValid)
            {
                var copyLibraryId = Convert.ToInt32(copyId.Replace("*", ""));
                var copy = await _db.Copies.FirstOrDefaultAsync(c => c.LibraryID == copyLibraryId);

                if (copy == null)
                    return Json(new { title = "No copy found with that ID." }, JsonRequestBehavior.AllowGet);

                return Json(new { title = copy.Game.Title }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { title = "Copy ID required." }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> SearchCopies(CopySearchViewModel model)
        {
            if (ModelState.IsValid)
            {
                int searchedID;
                bool isNumeric = int.TryParse(model.Info, out searchedID);
                var allMatchedCopies = new List<Copy>();
                var copiesMatchingTitle = await _db.Copies.Where(c => c.Game.Title.Contains(model.Info)).ToListAsync();
                if (isNumeric)
                {
                    var copiesMatchingID = await _db.Copies.Where(c => c.LibraryID == searchedID).ToListAsync();
                    allMatchedCopies.AddRange(copiesMatchingID);
                }

                allMatchedCopies.AddRange(copiesMatchingTitle);
                allMatchedCopies = allMatchedCopies.Distinct().ToList();

                if (model.NavSearch)
                    return PartialView("_CopyNavSearchResults", allMatchedCopies);

                return PartialView("_CopyList", allMatchedCopies);
            }
            else
                return GetModelStateErrorsJson();
        }

        public ActionResult ListCheckedOutCopies()
        {
            var checkedOutCopies = _db.Copies.Where(c => c.CurrentCheckout != null)
                                             .AsEnumerable()
                                             .OrderByDescending(c => c.CurrentCheckout.Length);

            return View(checkedOutCopies);
        }

        public ActionResult ListLongestCheckedOutCopies()
        {
            var checkedOutCopies = _db.Copies.Where(c => c.CurrentCheckout != null)
                                             .AsEnumerable()
                                             .OrderByDescending(c => c.CurrentCheckout.Length)
                                             .Take(10);

            return View("_LongestCheckedOutCopies", checkedOutCopies);
        }

        private JsonResult GetModelStateErrorsJson()
        {
            var errorList = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                );

            Response.StatusCode = 400;

            return Json(errorList, JsonRequestBehavior.AllowGet);
        }

        // POST: Copies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Copy copy = await _db.Copies.FindAsync(id);

BoardGameLibrary/Views/Shared/_CopyCheckIn.cshtml
@model BoardGameLibrary.Models.CopyCheckInViewModel

<div id="check-in-form-wrapper">
    @using (Ajax.BeginForm("CheckInCopy", "Copies",
                new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "check-in-form-wrapper", OnSuccess = "clearCheckInForm", OnFailure = "updateCheckInForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div id="check-in-notification-wrapper"  class="col-md-12 notification-wrapper">
                @if (Model.Messages.Any())
                {
                    <div class="notification-panel fade-in fade-out-delayed">
                        @foreach (var msg in Model.Messages)
                        {
                            <span class="notification fade-in fade-out-delayed">@msg</span>
                        }
                    </div>
                }
            </div>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CopyLibraryID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CopyLibraryID, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.CopyLibraryID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="Check In" class="btn btn-lg btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    var notificationWrapper = $('#check-in-notification-wrapper');
    setTimeout(function () {
        notificationWrapper.html('');
    }, 4100);

    $('a:contains(Check In)').on('click', function () {
        setTimeout(function () {
            $('#check-in-form-wrapper #CopyLibraryID').focus();
        }, 200)
    });
</script>

BoardGameLibrary/Views/Shared/_CopyCheckOut.cshtml
@model BoardGameLibrary.Models.CopyCheckOutViewModel

<div id="check-out-form-wrapper">
    @using (Ajax.BeginForm("CheckOutCopy", "Copies",
        new AjaxOptions
        {
            HttpMethod = "POST",
            UpdateTargetId = "check-out-form-wrapper",
            OnSuccess = "clearCheckOutForm",
            OnFailure = "updateCheckOutForm"
        }))
    {
        @Html.AntiForgeryToken()

        <div id="clear-checkout-form" class="form-horizontal">
            <div id="check-out-notification-wrapper" class="col-md-12 notification-wrapper">
                @if (Model.Messages.Any())
                {
                    <div class="notification-panel fade-in fade-out-delayed">
                        @foreach (var msg in Model.Messages)
                        {
                            <span class="notification fade-in fade-out-delayed">@msg</span>
                        }
                    </div>
                }
            </div>
            <br />
            <button id="btn-clear-checkout-form" type="reset" class="btn btn-default">Start Over</button>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CopyLibraryID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CopyLibraryID, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.CopyLibraryID, "", new { @class = "text-danger" })
                    <strong id="locatedGameTitle" class="floatleft green-text"></strong>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AttendeeBadgeID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AttendeeBadgeID, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.AttendeeBadgeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OverrideLimit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.OverrideLimit, new { @class = "form-control bigcheckbox" })
                    @Html.ValidationMessageFor(model => model.OverrideLimit, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="Check Out" class="btn btn-lg btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    var notificationWrapper = $('#check-out-notification-wrapper');
    setTimeout(function () {
        notificationWrapper.html('');
    }, 4100);

    $('#btn-clear-checkout-form').click(function (e) {
        e.preventDefault();

        $('#clear-checkout-form .text-box').val('');
        $('#OverrideLimit').removeAttr('checked');
        $('#CopyLibraryID').focus();
    });

    $('#CopyLibraryID').change(function () {
        var id = $("#CopyLibraryID").val();
        if (id.length >= 5) {
            $('#AttendeeBadgeID').focus();
        }
    });

    $("#CopyLibraryID").blur(function () {
        var id = $("#CopyLibraryID").val();
        if (id) {
            $.get('@Url.Action("GetCopyGameTitle", "Copies")', { copyId: id }, function (response) {
                $("#locatedGameTitle").text(response.title);
            });
        }
    });

    $('a:contains(Check Out)').on('click', function () {
        setTimeout(function () {
            $('#check-out-form-wrapper #CopyLibraryID').focus();
        }, 200)
    });
</script>

BoardGameLibrary/Views/Shared/_CopyList.cshtml
@model IEnumerable<BoardGameLibrary.Data.Models.Copy>

<table class="table table-condensed table-bordered table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Game.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LibraryID)
        </th>
        <th>
            Checked Out At
        </th>
        <th>
            Checked Out To
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    string rowClass;
    if (item.CurrentCheckout == null)
    {
        rowClass = "success";
    }
    else
    {
        rowClass = "danger";
    }
    <tr class="@rowClass">
        <td>
            @Html.DisplayFor(modelItem => item.Game.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LibraryID)
        </td>
        <td>
            @if (item.CurrentCheckout != null)
            {
                @Html.DisplayFor(modelItem => item.CurrentCheckout.TimeOut)
            }
        </td>
        <td>
            @if (item.CurrentCheckout != null)
            {
                @item.CurrentCheckout.Attendee.Name <text>(@item.CurrentCheckout.Attendee.BadgeID)</text>
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Copies", new { id = item.ID }, new { @class = "btn btn-sm btn-default" })
            @if (item.CurrentCheckout != null)
            {
                <button class="btn btn-sm btn-default" onclick="CheckInGame(@item.LibraryID)" value="Check In">Check In</button>
            }
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    function CheckInGame(id) {
        $.post('@Url.Action("CheckInCopyLight", "Copies")', { copyId: id }, function (response) {
            var message = response.message;
            var message = "<div class='notification-panel fade-in fade-out-delayed'><span class='notification fade-in fade-out-delayed'>" + message + "</span></div>";
            $("#CopySearchMessages").html(message);
            $("#btnSearch").click();
        });
    }
</script>

BoardGameLibrary/Views/Shared/_CopyNavSearch.cshtml
@using (Ajax.BeginForm("SearchCopies", "Copies", new { navsearch = true }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "copy-quick-search-results" }, new { @class = "navbar-form navbar-right" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <input id="copy-quick-search-text" name="info" type="text"  class="form-control" placeholder="Search game copies by title/ID..." autocomplete="off">
    </div>
    <div id="copy-quick-search-results" class="hidden">
    </div>
}

<script>
    var quickSearchInput = $('#copy-quick-search-text');
    var quickSearchResults = $('#copy-quick-search-results');
    quickSearchInput.keyup(function () {
        quickSearchResults.html('');
        if ((quickSearchInput).val().length > 2) {
            $('form.navbar-form.navbar-right').submit();
            quickSearchResults.removeClass('hidden');
        }
        else {
            quickSearchResults.addClass('hidden');
        }
    });

    quickSearchInput.focusout(function () {
        quickSearchInput.val('');
        quickSearchResults.addClass('hidden');
    });
</script>

BoardGameLibrary/Views/Shared/_CopyNavSearchResults.cshtml
@model IEnumerable<BoardGameLibrary.Data.Models.Copy>
<ul>
    @foreach (var item in Model)
    {
        string rowClass;
        if (item.CurrentCheckout == null)
        {
            rowClass = "success";
        }
        else
        {
            rowClass = "danger";
        }
        <li class="@rowClass">
            <h4>
                @Html.DisplayFor(modelItem => item.Game.Title) (@Html.DisplayFor(modelItem => item.LibraryID))
            </h4>
            
            @if (item.CurrentCheckout != null)
            {
                <small>
                    Checked out <strong>@Html.DisplayFor(modelItem => item.CurrentCheckout.TimeOut.DayOfWeek) at @item.CurrentCheckout.TimeOut.ToShortTimeString()</strong>
                    by <strong>@item.CurrentCheckout.Attendee.Name <text>(@item.CurrentCheckout.Attendee.BadgeID)</text></strong>
                </small>
            }
            else
            {
                <small>
                    Available
                </small>
            }
        </li>
    }
</ul>

BoardGameLibrary/Views/Shared/_CopySearch.cshtml
@model BoardGameLibrary.Models.CopySearchViewModel

@using (Ajax.BeginForm("SearchCopies", "Copies", new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "copy-search-results" }))
{
    @Html.AntiForgeryToken()
    <h4>Copy Search</h4>
    <div id="CopySearchMessages" class="notification-wrapper">

    </div>
    <div class="row">
        <div class="form col-md-4">
            <div class="row">
                <div class="col-md-3">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.Info, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Info, new { htmlAttributes = new { @class = "form-control input-sm" } })
                    @Html.ValidationMessageFor(model => model.Info, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <input id="btnSearch" type="submit" value="Search" class="btn btn-lg btn-primary" />
            
        </div>
        <div id="copy-search-results" class="col-md-8">
        </div>
    </div>
}

BoardGameLibrary/Views/Shared/_LongestCheckedOutCopies.cshtml
@model IEnumerable<BoardGameLibrary.Data.Models.Copy>

@{
    Layout = null;
}

<h3>Top 10 Longest Checkouts</h3>

<ol class="list-group longest-checkouts-table">
    @foreach (var item in Model)
    {
        
        var timespan = item.CurrentCheckout.Length;
        var checkoutStatusClass = "list-group-item-success";
        if (item.CurrentCheckout.Length > TimeSpan.FromHours(5))
        {
            checkoutStatusClass = "list-group-item-danger";
        }
        else if (item.CurrentCheckout.Length > TimeSpan.FromHours(3))
        {
            checkoutStatusClass = "list-group-item-warning";
        }
        
        <li class="list-group-item @checkoutStatusClass">
            <span class="list-group-item-text">
                @string.Format("{0} ({1}) - {2}d {3}h {4}m - {5} ({6})",
                    item.Game.Title, item.LibraryID,
                    timespan.Days, timespan.Hours, timespan.Minutes,
                    item.CurrentCheckout.Attendee.Name, item.CurrentCheckout.Attendee.BadgeID
                )
            </span>
        </li>
    }
</ol>