BoardGameLibrary/Models/Attendee.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BoardGameLibrary.Models
{
    public class Attendee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        [Display(Name = "Badge #")]
        public string BadgeID { get; set; }
        public virtual IList<Checkout> Checkouts { get; set; }
    }
}

BoardGameLibrary/Controllers/AttendeesController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BoardGameLibrary.Models;
using BoardGameLibrary.Data.Models;
using BoardGameLibrary.Utility;
using PagedList;

namespace BoardGameLibrary.Controllers
{
    public class AttendeesController : VolunteerController
    {
        private ApplicationDbContext _db;
        private AppSettings _appSettings;
        private FileUploader fileUploader;

        public AttendeesController()
        {
            _db = new ApplicationDbContext();
            fileUploader = new FileUploader(_db);
            _appSettings = new AppSettings();
        }

        public AttendeesController(ApplicationDbContext dbContext, AppSettings appSettings)
        {
            _db = dbContext;
            _appSettings = appSettings;
        }

        // GET: Attendees
        public async Task<ActionResult> Index(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;
            int pageSize = _appSettings.PageSize;
            int pageNumber = page ?? 1;
            ViewBag.Errors = TempData["ErrorList"];

            IQueryable<Attendee> attendees = _db.Attendees;

            if (!string.IsNullOrWhiteSpace(searchString))
                attendees = attendees.Where(a => a.Name.Contains(searchString) || a.BadgeID.Contains(searchString));

            var model = new AttendeeIndexViewModel();
            var orderedAttendees = attendees.OrderBy(a => a.Name).ToList();
            model.Attendees = orderedAttendees.ToPagedList(pageNumber, pageSize);

            return View(model);
        }

        // GET: Attendees/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Attendee Attendee = _db.Attendees.FirstOrDefault(a => a.ID == id.Value);
            if (Attendee == null)
                return HttpNotFound();

            return View(Attendee);
        }

        // GET: Attendees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Attendees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Name,BadgeID")] Attendee Attendee)
        {
            if (ModelState.IsValid)
            {
                _db.Attendees.Add(Attendee);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(Attendee);
        }

        // GET: Attendees/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Attendee Attendee = await _db.Attendees.FindAsync(id);
            if (Attendee == null)
                return HttpNotFound();

            return View(Attendee);
        }

        // POST: Attendees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,BadgeID")] Attendee Attendee)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(Attendee).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(Attendee);
        }

        [HttpPost]
        public ActionResult Import(AttendeeIndexViewModel model)
        {
            IList<string> errors;
            var importFile = model.File;
            if (importFile == null || importFile == null || importFile.ContentLength == 0)
            {
                if (importFile == null)
                    errors = new List<string> { "The server didn't receive the file." };
                else
                    errors = new List<string> { "The file contents were empty." };
            }
            else
            {
                // Upload attendees from the file.
                errors = fileUploader.UploadAttendees(importFile);
            }

            TempData["ErrorList"] = new ErrorList { Errors = errors };
            return RedirectToAction("Index");
        }

        // GET: Attendees/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Attendee Attendee = await _db.Attendees.FindAsync(id);
            if (Attendee == null)
                return HttpNotFound();

            return View(Attendee);
        }

        // POST: Attendees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Attendee Attendee = await _db.Attendees.FindAsync(id);
            _db.Attendees.Remove(Attendee);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _db.Dispose();

            base.Dispose(disposing);
        }
    }
}

BoardGameLibrary/Views/Attendees/Create.cshtml
@model BoardGameLibrary.Data.Models.Attendee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendee</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BadgeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BadgeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BadgeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success">
            </div>
        </div>
    </div>
}

BoardGameLibrary/Views/Attendees/Delete.cshtml
@model BoardGameLibrary.Data.Models.Attendee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attendee</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BadgeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BadgeID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

BoardGameLibrary/Views/Attendees/Details.cshtml
@model BoardGameLibrary.Data.Models.Attendee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Attendee</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BadgeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BadgeID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-default" })
</p>

BoardGameLibrary/Views/Attendees/Edit.cshtml
@model BoardGameLibrary.Data.Models.Attendee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendee</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BadgeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BadgeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BadgeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

BoardGameLibrary/Views/Attendees/Index.cshtml
@using PagedList.Mvc;
@model AttendeeIndexViewModel
@using BoardGameLibrary.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Attendees</h2>
@{
    ErrorList errorList = (ErrorList)ViewBag.Errors;
    if (errorList != null && errorList.Errors.Any())
    {

        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <strong>Errors</strong>
            <ul>
                @foreach (var err in errorList.Errors)
                {
                    <li>@err</li>
                }
            </ul>
        </div>
    }
}
<div class="row">
    <div class="col-md-1">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    </div>
    <div class="col-md-offset-1 col-md-4">
        @using (Html.BeginForm("Index", "Attendees", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="row">
                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control text-box col-md-1", placeholder = "Name or Badge ID" })
                <input type="submit" value="Search" class="btn btn-primary col-md-3" />
            </div>
        }
    </div>
    
    @if (User.IsInRole("AdminUI-Admin"))
    {
        <div class="col-md-offset-1 col-md-5">
            @using (Html.BeginForm("Import", "Attendees", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-inline">
                    <div class="form-group width50pct">
                        <input type="file" class="filestyle" data-buttontext=" Browse..." data-buttonname="btn-primary" data-buttonbefore="true" name="File" />
                    </div>
                    <input type="submit" name="submit" class="btn btn-success" value="Import" />
                </div>
            }
        </div>
    }
</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Attendees[0].Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Attendees[0].BadgeID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Attendees) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BadgeID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-default btn-sm" })
            @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-default btn-sm" })
            @*@Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })*@
        </td>
    </tr>
}

</table>
<br />
Page @(Model.Attendees.PageCount < Model.Attendees.PageNumber ? 0 : Model.Attendees.PageNumber) of @Model.Attendees.PageCount

@Html.PagedListPager(Model.Attendees, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))

@section Scripts{
    <script src="~/Scripts/bootstrap-filestyle.min.js"></script>
}